export const commandsNames = {
  italic: 'italic',
  bold: 'bold',
  underline: 'underline',
  code: 'code',
  codeBlock: 'codeBlock',
  left: 'left',
  center: 'center',
  right: 'right',
  justify: 'justify',
  bulletList: 'bulletList',
  orderedList: 'orderedList',
  subscript: 'subscript',
  superscript: 'superscript',
};

export const buttonsHeadings = {
  italic: 'Курсив',
  bold: 'Жирный',
  underline: 'Подчеркивание',
  code: 'Код',
  codeBlock: 'Блок кода',
  left: 'Выровнять по левому краю',
  center: 'Выровнять по центру',
  right: 'Выровнять по правому краю',
  justify: 'Выровнять по ширине',
  bulletList: 'Маркированный список',
  orderedList: 'Нумерованный список',
  subscript: 'Нижний индекс',
  superscript: 'Верхний индекс',
};
